REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

source $REPO_ROOT/dex/generated/dex.env
#echo "$LIBCLOUD_OIDC_CLIENT_SECRET"

# Per-cloud user passwords are generated by dex_bootstrap.py into
# dex/generated/dex.env (sourced on line 1) on every setup.sh run. Do NOT
# hardcode them here — stale values from a previous run cause Dex 401s.
# AWS backend credentials for the tenant:aws owner write below.

#LIBCLOUD_OIDC_CLIENT_SECRET=${LIBCLOUD_OIDC_CLIENT_SECRET} TENANT=aws LIBCLOUD_USER=aws-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_AWS_OWNER \
#    LIBCLOUD_AWS_KEY=${AWS_ACCESS_KEY} LIBCLOUD_AWS_SECRET=${AWS_SECRET_ACCESS_KEY} \
#    python3 test_script/scripts/set_tenant_credentials.py

#LIBCLOUD_OIDC_CLIENT_SECRET=${LIBCLOUD_OIDC_CLIENT_SECRET} TENANT=nutanix LIBCLOUD_USER=ntnx-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_NTNX_OWNER \
#    LIBCLOUD_NTNX_USER=admin LIBCLOUD_NTNX_PASSWORD=admin \
#    python3 test_script/scripts/set_tenant_credentials.py
##superadmin (owner on both tenants) can set them too.

##Then run:
LIBCLOUD_USER=aws-viewer  $REPO_ROOT/test_script/./scripts/provision_aws.sh
LIBCLOUD_USER=aws-admin PROVISION=1 $REPO_ROOT/test_script/./scripts/provision_aws.sh
LIBCLOUD_USER=aws-admin $REPO_ROOT/test_script/./scripts/deprovision_aws.sh

LIBCLOUD_USER=ntnx-admin PROVISION=1 $REPO_ROOT/test_script/scripts/provision_nutanix.sh
LIBCLOUD_USER=ntnx-viewer $REPO_ROOT/test_script/scripts/provision_nutanix.sh
LIBCLOUD_USER=ntnx-admin $REPO_ROOT/test_script/scripts/deprovision_nutanix.sh
