HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1423
Date: Wed, 23 Jul 2026 14:22:12 GMT

{
  "tuples": [
    {
      "key": {
        "user": "user:superadmin",
        "relation": "superadmin",
        "object": "platform:main"
      }
    },
    {
      "key": {
        "user": "user:aws-admin",
        "relation": "admin",
        "object": "tenant:aws"
      }
    },
    {
      "key": {
        "user": "user:ntnx-owner",
        "relation": "owner",
        "object": "tenant:nutanix"
      }
    },
    {
      "key": {
        "user": "user:aws-viewer",
        "relation": "viewer",
        "object": "tenant:aws"
      }
    },
    {
      "key": {
        "user": "user:superadmin",
        "relation": "can_read",
        "object": "aws_region:aws"
      }
    },
    {
      "key": {
        "user": "user:superadmin",
        "relation": "can_read",
        "object": "nutanix_cluster:nutanix"
      }
    },
    {
      "key": {
        "user": "user:aws-admin",
        "relation": "can_provision",
        "object": "aws_region:aws"
      }
    },
    {
      "key": {
        "user": "user:aws-admin",
        "relation": "can_update",
        "object": "aws_region:aws"
      }
    }
  ],
  "continuation_token": ""
}
