source dex/generated/dex.env
echo "$LIBCLOUD_OIDC_CLIENT_SECRET"

##
##echo "  superadmin   / ${LIBCLOUD_SUPERADMIN_PASSWORD}   (bootstrap: Vault/OpenFGA/LLDAP admin)"
##echo "  aws-owner    / ${LIBCLOUD_PASSWORD_AWS_OWNER}    (owner  of tenant:aws)"
##echo "  aws-admin    / ${LIBCLOUD_PASSWORD_AWS_ADMIN}    (admin  of tenant:aws -> provision AWS)"
##echo "  aws-viewer   / ${LIBCLOUD_PASSWORD_AWS_VIEWER}   (viewer of tenant:aws -> enumerate only)"
##echo "  ntnx-owner   / ${LIBCLOUD_PASSWORD_NTNX_OWNER}   (owner  of tenant:nutanix)"
##echo "  ntnx-admin   / ${LIBCLOUD_PASSWORD_NTNX_ADMIN}   (admin  of tenant:nutanix -> provision Nutanix)"
##echo "  ntnx-viewer  / ${LIBCLOUD_PASSWORD_NTNX_VIEWER}  (viewer of tenant:nutanix -> enumerate only)"
##echo "  cloud-denied / ${LIBCLOUD_PASSWORD_CLOUD_DENIED} (authenticated but denied)"
##  superadmin   / SA-M6jUCJdcQ4d7ultmb4YDU2hJ   (bootstrap: Vault/OpenFGA/LLDAP admin)
##  aws-owner    / SA-eA0HA7pmUWiW-C6sxyC5xt02    (owner  of tenant:aws)
##  aws-admin    / SA-qxlKEpt9SR2N8llPxSXwyWex    (admin  of tenant:aws -> provision AWS)
##  aws-viewer   / SA-UbCyrwJuoTR0tmjIykZdL45h   (viewer of tenant:aws -> enumerate only)
##  ntnx-owner   / SA-KM8ACXQngqj3kVFFS0mIwSz-   (owner  of tenant:nutanix)
##  ntnx-admin   / SA-31ALF-5Qw251zwpErUqe-GR4   (admin  of tenant:nutanix -> provision Nutanix)
##  ntnx-viewer  / SA-cTxX4VA3av2J4-zK1lgt3IE4  (viewer of tenant:nutanix -> enumerate only)
##  cloud-denied / CloudDenied123! (authenticated but denied)

# Per-cloud user passwords are generated by dex_bootstrap.py into
# dex/generated/dex.env (sourced on line 1) on every setup.sh run. Do NOT
# hardcode them here — stale values from a previous run cause Dex 401s.
# AWS backend credentials for the tenant:aws owner write below.
AWS_ACCESS_KEY=AKIAYHGEH2P7SNGEPLZH
AWS_SECRET_ACCESS_KEY=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

LIBCLOUD_OIDC_CLIENT_SECRET=${LIBCLOUD_OIDC_CLIENT_SECRET} TENANT=aws LIBCLOUD_USER=aws-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_AWS_OWNER \
    LIBCLOUD_AWS_KEY=${AWS_ACCESS_KEY} LIBCLOUD_AWS_SECRET=${AWS_SECRET_ACCESS_KEY} \
    python3 test_script/scripts/set_tenant_credentials.py

LIBCLOUD_OIDC_CLIENT_SECRET=${LIBCLOUD_OIDC_CLIENT_SECRET} TENANT=nutanix LIBCLOUD_USER=ntnx-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_NTNX_OWNER \
    LIBCLOUD_NTNX_USER=admin LIBCLOUD_NTNX_PASSWORD=admin \
    python3 test_script/scripts/set_tenant_credentials.py
##superadmin (owner on both tenants) can set them too.

##Then run:
  #LIBCLOUD_USER=aws-viewer  test_script/./scripts/provision_aws.sh 1>/tmp/1 2>/tmp/2
  #LIBCLOUD_USER=aws-admin PROVISION=1 test_script/./scripts/provision_aws.sh
  #LIBCLOUD_USER=aws-admin test_script/./scripts/deprovision_aws.sh
  #
  LIBCLOUD_USER=ntnx-admin PROVISION=1 test_script/./scripts/provision_nutanix_private.sh
  #LIBCLOUD_USER=ntnx-viewer test_script/./scripts/provision_nutanix_private.sh
  #LIBCLOUD_USER=ntnx-admin test_script/./scripts/deprovision_nutanix.sh
  exit

file                                                                                                                 0.0s
[+] up 2/2
 ✔ Image libcloud-rest-api:latest Built                                                                                                                     1.3s
 ✔ Container libcloud-rest-api    Started                                                                                                                   1.0s

Setup complete.
  OpenFGA env  : /home/ubuntu/libcloud_nutanix/openfga_postgres/generated/fga.env
  Postgres env : /home/ubuntu/libcloud_nutanix/test_script/generated/postgres.env  (datastore: postgres://openfga@postgres:5432/openfga)
  Dex OIDC     : /home/ubuntu/libcloud_nutanix/openfga_postgres/../dex/generated/dex.env
  Vault        : /home/ubuntu/libcloud_nutanix/openfga_postgres/../vault/generated/vault.env

Identity model:
  superadmin   / SA-M6jUCJdcQ4d7ultmb4YDU2hJ   (bootstrap: Vault/OpenFGA/LLDAP admin)
  aws-owner    / SA-eA0HA7pmUWiW-C6sxyC5xt02    (owner  of tenant:aws)
  aws-admin    / SA-qxlKEpt9SR2N8llPxSXwyWex    (admin  of tenant:aws -> provision AWS)
  aws-viewer   / SA-UbCyrwJuoTR0tmjIykZdL45h   (viewer of tenant:aws -> enumerate only)
  ntnx-owner   / SA-KM8ACXQngqj3kVFFS0mIwSz-   (owner  of tenant:nutanix)
  ntnx-admin   / SA-31ALF-5Qw251zwpErUqe-GR4   (admin  of tenant:nutanix -> provision Nutanix)
  ntnx-viewer  / SA-cTxX4VA3av2J4-zK1lgt3IE4  (viewer of tenant:nutanix -> enumerate only)
  cloud-denied / CloudDenied123! (authenticated but denied)

Datastore: PostgreSQL (container openfga-postgres, volume openfga_postgres-pg-data / openfga-pg-data).
Inspect tuples via SQL:
  docker exec -it openfga-postgres psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'select count(*) from tuple;'

OpenFGA image: openfga-local:latest, built from ./Dockerfile by openfga_postgres/setup.sh.

Cloud backend credentials are per-tenant and NOT set by setup.sh.
Each tenant's OWNER writes its credentials to Vault (gated by OpenFGA
can_manage_credentials; admins/viewers cannot):
  TENANT=aws LIBCLOUD_USER=aws-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_AWS_OWNER \
    LIBCLOUD_AWS_KEY=AKIA... LIBCLOUD_AWS_SECRET=... \
    python3 scripts/set_tenant_credentials.py
  TENANT=nutanix LIBCLOUD_USER=ntnx-owner LIBCLOUD_PASSWORD=$LIBCLOUD_PASSWORD_NTNX_OWNER \
    LIBCLOUD_NTNX_USER=admin LIBCLOUD_NTNX_PASSWORD=... \
    python3 scripts/set_tenant_credentials.py
superadmin (owner on both tenants) can set them too.

