POST /auth/simple/login HTTP/1.1
Host: lldap:17170
Content-Type: application/json
Accept: application/json
Content-Length: 61

{
  "username": "admin",
  "password": "EXAMPLE_LLDAP_ADMIN_PASSWORD_12345678"
}
