HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 170
Date: Wed, 23 Jul 2026 14:29:06 GMT

{
  "users": [
    {"object": {"type": "user", "id": "eng-owner"}},
    {"object": {"type": "user", "id": "eng-viewer"}}
  ]
}
