HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store
Pragma: no-cache
Content-Length: 1427
Date: Wed, 23 Jul 2026 14:22:03 GMT

{
  "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjExMjIzMzQ0NTU2Njc3ODg5OSJ9.eyJpc3MiOiJodHRwOi8vbG9naW4ucXVlc3Q0c2NpZW5jZS54eXo6NTU1Ni9kZXgiLCJzdWIiOiJDaVFnVDFKVVJWOVVWVkZPSUZKQlRrVlYiLCJhdWQiOiJsaWJjbG91ZC1wb3J0YWwiLCJleHAiOjE3NTM0OTA1MjEsImlhdCI6MTc1MzQ4NjkyMSwiYXRfaGFzaCI6ImFiYzEyMyIsImVtYWlsIjoiYXdzLWFkbWluQGxpYmNsb3VkLmxvY2FsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJBV1MgQWRtaW4ifQ.SIGNATURE",
  "token_type": "bearer",
  "expires_in": 3600,
  "refresh_token": "ChlDZXgtcmVmcmVzaC10b2tlbi1leGFtcGxlLTEyMzQ1Njc4OTBhYmNkZWY",
  "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjExMjIzMzQ0NTU2Njc3ODg5OSJ9.eyJpc3MiOiJodHRwOi8vbG9naW4ucXVlc3Q0c2NpZW5jZS54eXo6NTU1Ni9kZXgiLCJzdWIiOiJDaVFnVDFKVVJWOVVWVkZPSUZKQlRrVlYiLCJhdWQiOiJsaWJjbG91ZC1wb3J0YWwiLCJleHAiOjE3NTM0OTA1MjEsImlhdCI6MTc1MzQ4NjkyMSwibm9uY2UiOiJhYmMxMjMiLCJhdF9oYXNoIjoiZGVmNDU2IiwiZW1haWwiOiJhd3MtYWRtaW5AbGliY2xvdWQubG9jYWwiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkFXUyBBZG1pbiJ9.SIGNATURE"
}
