HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 403
Date: Wed, 23 Jul 2026 14:30:15 GMT

{
  "internalUserId": "int-aws-admin",
  "role": "admin",
  "linkedIdentities": [
    "lldap:CiQgT1JURV9VU0VFOkJMQk9DSw=="
  ],
  "email": "aws-admin@libcloud.local",
  "clouds": [
    {
      "cloud": "aws",
      "canView": true,
      "canProvision": true,
      "canUpdate": true
    },
    {
      "cloud": "nutanix",
      "canView": true,
      "canProvision": false,
      "canUpdate": false
    }
  ]
}
