HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 587
Date: Wed, 23 Jul 2026 14:22:01 GMT

{
  "authorizeUrl": "http://login.cloudweave.xyz:5556/dex/auth?client_id=libcloud-portal&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email&state=aB3kXp9qR7sW2vY6uN1mF4dG8jL0oQ5t&code_challenge=KzP9wLm2xR7vQ4nJ8sA1dF6gH0kT3yB5&code_challenge_method=S256&connector_id=lldap",
  "state": "aB3kXp9qR7sW2vY6uN1mF4dG8jL0oQ5t",
  "provider": "lldap"
}
